### ISSUE TITLE
Gemspec issue when installing with Bundler 1.10.6

### ISSUE THREAD

**Issue by whitecl** [expectedbehavior/cheddargetter_client_ruby#10]
I get the following error when installing cheddargetter_client_ruby via bundler 1.10.6 after running bundle install and then 'bundle show cheddargetter_client_ruby'

The error does not occur when using bundler 1.9.5

```
The gemspec at /Users/chris/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/cheddargetter_client_ruby-77e3187e27e7/cheddargetter_client_ruby.gemspec is not valid. The validation error was 'duplicate dependency on httparty (>= 0.4.3), (>= 0.4.3) use:
    add_runtime_dependency 'httparty', '>= 0.4.3', '>= 0.4.3'
'
Could not find cheddargetter_client_ruby-0.3.2 in any of the sources
```

**Comment by marcguyer** [comment]
I see that there are duplicate dependencies declared in the gemspec. I'm guessing later versions of bundler are less tolerant of such abhorrent oversights.

**Comment by marcguyer** [comment]
@whitecl Would you like to update it to the latest?

**Comment by whitecl** [comment]
@marcguyer will have a look at this sometime over the next few days.
