### ISSUE TITLE
Use canonical attribute names?

### ISSUE THREAD

**Issue by alexkwolfe** [expectedbehavior/cheddargetter_client_ruby#2]
Have you thought about using canonical attribute names, with underscores instead of camel-back case with no underscores?  I realize that the CG API uses camel-back case attribute names, but this is at odds with canonical ruby style.

I would be nice if the gem encapsulated the logic required to create the correct attribute name case for CG, so that the gem consumer can use parameter with underscores as usual.

I could contribute a patch if you're interested.

**Comment by jqr** [comment]
Seems like conversion is left out on purpose, and it's been 5 years, closing.
